name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-linux-hlsdk-xash3d:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build linux
      run: |
        git submodule init && git submodule update
        #sudo apt install build-essential libsdl2-dev libfontconfig-dev libfreetype6-dev -y
        #wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
        #export ANDROID_NDK_HOME=$PWD/android-sdk-r24.4.1/
        #export NDK_HOME=$PWD/android-sdk-r24.4.1/
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
        unzip android-ndk-r10e-linux-x86_64.zip
        export ANDROID_NDK_HOME=$PWD/android-ndk-r10e/
        export NDK_HOME=$PWD/android-ndk-r10e/
        mkdir ./out
        ./waf configure -T release --android=armv7a-hard,host,21 --prefix=./out
        ./waf install
    - uses: actions/upload-artifact@v3
      with:
        name: hlsdk-xash3d-upload
        path: ./out
        if-no-files-found: error
