name: build ARM64

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build with CMake (ARM64)
      shell: cmd
      run: |
        cmake -B build -G "Visual Studio 17 2022" -A ARM64 -DCMAKE_INSTALL_PREFIX="dist"
        cmake --build build --config Release --target all
        cmake --build build --config Release --target install

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-windows-arm64
        path: dist/
