name: Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-linux-hlsdk-xash3d:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build linux
      run: |
        git submodule init && git submodule update
        #sudo apt install build-essential libsdl2-dev libfontconfig-dev libfreetype6-dev -y
        #wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
        #export ANDROID_NDK_HOME=$PWD/android-sdk-r24.4.1/
        #export NDK_HOME=$PWD/android-sdk-r24.4.1/
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
        unzip android-ndk-r10e-linux-x86_64.zip
        export ANDROID_NDK_HOME=$PWD/android-ndk-r10e/
        export NDK_HOME=$PWD/android-ndk-r10e/
        ./waf configure -T release --android=aarch64,host,21
        ./waf build
        # sudo dpkg --add-architecture i386
        # sudo apt-get update
        # sudo apt-get install -f -y libopenal-dev:i386 g++-multilib gcc-multilib libpng-dev:i386 libjpeg-dev:i386 libfreetype6-dev:i386 libfontconfig1-dev:i386 libcurl4-gnutls-dev:i386 libsdl2-dev:i386 zlib1g-dev:i386 libbz2-dev:i386 libedit-dev:i386
        # PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig ./waf configure -T release --build-game=hl2mp
        # ./waf build
        # ls -la
        # mkdir ./build1
        # mkdir ./build1/bin
        # mkdir ./build1/game
        # mkdir ./build1/game/bin
        # find ./build -name "*.so" -exec mv -t ./build1/bin {} +
        # find ./build -name "libclient.so" -exec mv -t ./build1/game/bin {} +
        # find ./build -name "libserver.so" -exec mv -t ./build1/game/bin {} +
        # find ./build -name "*_launcher" -exec mv -t ./build1 {} +
        # rm -rf build
        # mv ./build1 ./build
    - uses: actions/upload-artifact@v3
      with:
        name: hlsdk-xash3d
        path: ./build
        if-no-files-found: error
